baseURL: "http://9akashnp8.github.io/blog/"
languageCode: en-us
title: "9akashnp8's Blog"
theme: "PaperMod"

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20